"""create model calls table

Revision ID: 53a1e9359693
Revises: 9700a03bbbb8
Create Date: 2026-08-02 20:17:12.042390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a1e9359693'
down_revision: Union[str, Sequence[str], None] = '9700a03bbbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('requested_model', sa.String(length=100), nullable=False),
    sa.Column('actual_model', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=30), server_default='fast', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ttft_seconds', sa.Float(), nullable=True),
    sa.Column('total_latency_seconds', sa.Float(), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_created_at'), 'model_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_calls_provider'), 'model_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_model_calls_request_id'), 'model_calls', ['request_id'], unique=True)
    op.create_index(op.f('ix_model_calls_requested_model'), 'model_calls', ['requested_model'], unique=False)
    op.create_index(op.f('ix_model_calls_status'), 'model_calls', ['status'], unique=False)
    op.create_index(op.f('ix_model_calls_user_id'), 'model_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_calls_user_id'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_status'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_requested_model'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_request_id'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_provider'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_created_at'), table_name='model_calls')
    op.drop_table('model_calls')
    # ### end Alembic commands ###
